site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
plugins:
  - search
  - tags
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - About: about.md
  - Learning Phase: learning.md
  - Mini Projects:
    - Frozen Lake: miniproj/frozenlake.md
    - Taxi: miniproj/taxi.md
    - Rule based SUMO: miniproj/rulebased_sumo.md
  - Single Intersection: 
    - Q Learning: single/qlearning.md
    - DQN: single/dqn.md
    - Rule based SUMO: single/ppo.md
    - Genetic Algo: single/gen.md
  - Multiple Intersection: 
    - MAPPO Cooperative: multi/mappo_cop.md
    - MAPPO Independent: multi/mappo_ind.md
  - OpenCV: cv.md